[package]
name = "machine_learning_proof"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
ndarray = "0.15.6"
linfa = "0.7.0"
linfa-trees ="0.7" 
ndarray-rand = "0.15.0"
plotters = "0.3.7"
